Select Name from Products;
Select Name,Price from Products;
Select Name from Products where Price <= 200;
Select * from Products where Price < 120 and Price > 60;
Select Name, Price * 100 from Products;
Select AVG(Price) from Products;
Select AVG(Price) from Products where Manufacturer = 2;
Select Count(*) from Products where Price >= 180;
Select Name, Price from Products where Price >= 180 Order by Price Desc, Name;
Select * from Products Inner Join Manufacturers on Products.Manufacturer = Manufacturers.Code;
Select Products.Name, Price, Manufacturers.Name from Products Inner Join Manufacturers on Products.Manufacturer = Manufacturers.Code;
Select Manufacturers.Name, AVG(Price) from Products Group By Manufacturer;
Select Manufacturers.Name, AVG(Price) from Products Inner Join Manufacturers on Products.Manufacturer = Manufacturers.Code Group By Manufacturers.Name;
Select Manufacturers.Name, AVG(Price) from Products Inner Join Manufacturers on Products.Manufacturer = Manufacturers.Code Group By Manufacturers.Name Having AVG(Price) >= 150;
Select Name, Price from Products Order By Price ASC Limit 1;
Select Manufacturers.Name, Products.Name, Price from Products Inner Join Manufacturers on Products.Manufacturer = Manufacturers.Code and Price = (Select Max(Price) From Products where Products.Manufacturer = Manufacturers.Code);
Insert Into Products (Name, Price, Manufacturer) Values (Loudspeakers, 70, 2);
Update Products Set Name = "Laser Printer" where Code = 8;
Update Products Set Price = Price * .9;
Update Products Set Price = Price * .9 where Price >= 120;